### PR TITLE
Lesson 1 2

### PR DESCRIPTION
**Pull request by hvd28**

### CODE REVIEW

**Comment by Jkuffler** [comment]
This works; however, the error being thrown here comes from ToDoList.js. In the return statement for the `.map()` you have incorrectly called the `id` prop. Fixing that means the error (see below) will stop appearing.

### Error from the console:
`react-jsx-dev-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TodoList`. See https://reactjs.org/link/warning-keys for more information.
    at li
    at TodoList
    at div
    at App`

**Comment by hvd28** [comment]
Hi! Thanks so much for the feedback, however I'm a little embarrassed to admit I'm not sure what you mean. I don't expect you to hand me the answer, but could you try to tell me that again with different wording, maybe?

**Comment by hvd28** [comment]
@Jkuffler OH - was the issue that I was using key={item.objectID} instead of key={item.id}?

**Comment by Jkuffler** [comment]
> @Jkuffler OH - was the issue that I was using key={item.objectID} instead of key={item.id}?

Exactamundo! Superb work in spotting that :)

**Pull request merged**
